name: Static Code Analysis

on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:
    branches:
      - main

jobs:
  sca:
    name: SCA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup DDEV
      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1

      # Install dependencies
      - name: Install Composer dependencies
        run: |
          ddev composer config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          ddev composer install

      - name: PHP lint
        run: ddev composer ci:php:lint

      - name: PHP CS Fixer
        run: ddev composer ci:php:fixer
        continue-on-error: true

      - name: PHPStan
        run: ddev composer ci:php:stan

      - name: XML lint
        run: ddev composer ci:xml:lint

      - name: YAML lint
        run: ddev composer ci:yaml:lint
