name: Static Code Analysis

on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:
    branches:
      - main

jobs:

  sca:
    uses: maikschneider/reusable-workflows/.github/workflows/sca.yml@main
    with:
      php-version: 8.1
