name: Tests

on:
  push:
    branches:
      - main
      - 'renovate/**'
      - unit-tests
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }})
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306
    strategy:
      fail-fast: false
      matrix:
        typo3-version: [ "11.5", "12.4" ]
        php-version: [ "7.4", "8.1", "8.2", "8.3" ]
        exclude:
          - typo3-version: "12.4"
            php-version: "7.4"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --with=typo3/cms-core:"^${{ matrix.typo3-version }}"

      - name: Run functional and unit tests
        run: |
          composer test:functional
          composer test:unit
        env:
          typo3DatabaseHost: '127.0.0.1'
          typo3DatabaseUsername: root
          typo3DatabasePort: 3306
          typo3DatabasePassword: root
          typo3DatabaseName: db

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: phpunit-bridge
          coverage: xdebug
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      # Run tests
      - name: Run tests
        run: composer test:coverage
        env:
          XDEBUG_MODE: coverage
          typo3DatabaseHost: '127.0.0.1'
          typo3DatabaseUsername: root
          typo3DatabasePort: 3306
          typo3DatabasePassword: root
          typo3DatabaseName: db

      # Report coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/clover-unit.xml,./coverage/clover-functional.xml
