name: Tests

on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:
    branches:
      - main
      - v13

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        typo3-version: [ "11.5.37", "12.4", "13.1" ]
        php-version: [ "7.4", "8.1", "8.2", "8.3" ]
        exclude:
          - typo3-version: "12.4"
            php-version: "7.4"
          - typo3-version: "13.1"
            php-version: "7.4"
          - typo3-version: "13.1"
            php-version: "8.1"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql

      # Setup DDEV
      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: false
      - name: Configure and start DDEV
        run: |
          ddev config --project-type=typo3 --php-version=${{ matrix.php-version }} --webimage-extra-packages=
          ddev start

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --with=typo3/cms-core:"^${{ matrix.typo3-version }}"

      # Fix namespace (add"/Support" to end of namespace) only for typo3-version 11
      - name: Fix codeception.yml namespace
        run: sed -i '1s/$/\\Support/' codeception.yml
        if: matrix.php-version == '7.4'

      # Init TYPO3
      - name: Init TYPO3
        run: ddev init-typo3

      # Run tests
      - name: Run acceptance tests
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 10
          command: ddev composer test:acceptance
          new_command_on_retry: ddev composer test:acceptance -- -g failed
      - name: Run functional and unit tests
        run: |
          ddev composer test:functional
          ddev composer test:unit

      # Save acceptance reports
      - uses: actions/upload-artifact@v4
        with:
          name: acceptance-reports-${{ matrix.php-version }}-${{ matrix.typo3-version }}
          path: Tests/Acceptance/_output
        if: failure()

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: none

      # Setup DDEV
      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: false
      - name: Configure and start DDEV
        run: |
          ddev config --project-type=typo3 --xdebug-enabled=true --web-environment-add="XDEBUG_MODE=coverage"
          ddev start

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      # Init TYPO3
      - name: Init TYPO3
        run: ddev init-typo3

      # Run tests
      - name: Run tests
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 10
          command: ddev composer test:coverage

      # Report coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/clover-unit.xml,./coverage/clover-functional.xml,./Tests/Acceptance/_output/coverage.xml
