name: Tests

on:
  push:
    branches:
      - main
      - 'renovate/**'
      - unit-tests
  pull_request:
    branches:
      - main

jobs:
  tests2:
    name: Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }} & ${{ matrix.dependencies }} dependencies)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.2", "8.3" ]
        typo3-version: [ "12.4" ]
        dependencies: [ "highest", "lowest" ]
        exclude:
          - php-version: "8.1"
            typo3-version: "13.1"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: none

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --with=typo3/cms-core:"^${{ matrix.typo3-version }}"

      # Run tests
      #      - name: Run acceptance tests
      #        uses: nick-fields/retry@v3
      #        with:
      #          max_attempts: 3
      #          retry_on: error
      #          timeout_minutes: 10
      #          command: composer test:acceptance
      #          new_command_on_retry: composer test:acceptance -- -g failed
      - name: Run functional and unit tests
        run: |
          composer test:functional
          composer test:unit

      # Save acceptance reports
  #      - uses: actions/upload-artifact@v4
  #        with:
  #          name: acceptance-reports-${{ matrix.php-version }}-${{ matrix.typo3-version }}-${{ matrix.dependencies }}
  #          path: log/acceptance-reports
  #        if: failure()

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    container: ghcr.io/xima-media/php8.2-composer:2.7.6
    services:
      db:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      # Run tests
      - name: Run tests
        run: composer test:coverage
        env:
          XDEBUG_MODE: coverage
          typo3DatabaseHost: 127.0.0.1
          typo3DatabaseUsername: root
          typo3DatabasePassword: root
          typo3DatabaseName: db

      # Upload artifact
#      - name: Fix coverage path
#        working-directory: coverage
#        run: sed -i 's#/var/www/html#${{ github.workspace }}#g' clover.xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/clover.xml
          retention-days: 7

#      # Save acceptance reports
#      - uses: actions/upload-artifact@v4
#        with:
#          name: acceptance-reports-coverage
#          path: log/acceptance-reports
#        if: failure()

  coverage-report:
    name: Report test coverage
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Download artifact
      - name: Download coverage artifact
        id: download
        uses: actions/download-artifact@v4
        with:
          name: coverage

      # CodeClimate
      - name: CodeClimate report
        uses: paambaati/codeclimate-action@v8.0.0
        if: env.CC_TEST_REPORTER_ID
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ steps.download.outputs.download-path }}/clover.xml:clover

      # Coveralls
      - name: Coveralls report
        uses: coverallsapp/github-action@v2
        with:
          file: ${{ steps.download.outputs.download-path }}/clover.xml
